name: flutter_library_task
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_linkify: ^5.0.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.3
  hooks_riverpod: ^1.0.0
  http: ^0.13.5
  pin_code_fields: ^7.4.0
  scrollable_list_tabview: ^0.1.6
  shared_preferences: ^2.0.17
  sprintf: ^7.0.0
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/animation/
    - assets/svgs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/img/Group.png
        - asset: assets/fonts/img/pdf.png
        - asset: assets/fonts/img/vid.png
    - family: ReemKufi
      fonts:
        - asset: assets/fonts/ReemKufi-Regular.ttf
